-- liquibase formatted sql

CREATE TABLE sensor
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    state     VARCHAR(255),
    captor_id BIGINT,
    CONSTRAINT pk_sensor PRIMARY KEY (id)
);

ALTER TABLE sensor
    ADD CONSTRAINT uc_sensor_captor UNIQUE (captor_id);

