CREATE TABLE temperature_captor
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sensor_id BIGINT,
    CONSTRAINT pk_temperature_captor PRIMARY KEY (id)
);

ALTER TABLE temperature_captor
    ADD CONSTRAINT uc_temperature_captor_sensor UNIQUE (sensor_id);

ALTER TABLE temperature_captor
    ADD CONSTRAINT FK_TEMPERATURE_CAPTOR_ON_SENSOR FOREIGN KEY (sensor_id) REFERENCES sensor (id);

ALTER TABLE sensor
    ADD CONSTRAINT FK_SENSOR_ON_CAPTOR FOREIGN KEY (captor_id) REFERENCES temperature_captor (id);