CREATE TABLE temperature_data
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    captor_id BIGINT                                  NOT NULL,
    measure   DECIMAL,
    degree    VARCHAR(10),
    timestamp DATE,
    CONSTRAINT pk_temperature_data PRIMARY KEY (id)
);

ALTER TABLE temperature_data
    ADD CONSTRAINT FK_TEMPERATURE_DATA_ON_CAPTOR FOREIGN KEY (captor_id) REFERENCES temperature_captor (id);